version: "2"

services:
  web:
    image: node
    volumes: 
      - .:/app
    working_dir: /app
    command: npm run dev
    depends_on: 
      - "mongodb"
    # build: .
    # ports: 
    #   - "3000:3000"
  mongodb:
    container_name: 'mongodb'
    image: mongo
    volumes: 
      - ./mongo/data:/data/db
      - ./mongo/logs:/data/logs
    ports: 
      - "27017:27017"
  nginx:
    restart: always
    image: nginx  
    container_name: nginx
    volumes: 
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/valr/log/nginx
    ports: 
      - 80:80
    links: 
      - "web"